stages:
  - build
  - security-scan

build container image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
        --no-push
        --destination app
        --tar-path app.tar
  artifacts:
    paths:
      - app.tar

static code analysis:
  stage: security-scan
  image: returntocorp/semgrep
  script:
    - semgrep scan 
        --config auto
        --error
        --output reports/semgrep-report.json
        --gitlab-sast
        "${CI_PROJECT_DIR}"
  # Normally you would not allow failures, but this makes it explicit that the scan succeeded, while issues are found.
  allow_failure:
    exit_codes:
      - 1  # means a successful scan, but with found issues. Otherwise it would exit 2
  artifacts:
    reports:
      sast: reports/semgrep-report.json

open source libraries:
  stage: security-scan
  image:
    name: aquasec/trivy
    entrypoint: [ "" ]
  script:
    - trivy filesystem "${CI_PROJECT_DIR}"
        --no-progress
        --include-dev-deps
        --severity MEDIUM,HIGH,CRITICAL
        --exit-code 42
  # Normally you would not allow failures, but this makes it explicit that the scan succeeded, while issues are found.
  allow_failure:
    exit_codes:
      - 42

container image:
  stage: security-scan
  image:
    name: aquasec/trivy
    entrypoint: [ "" ]
  script:
    - trivy image
      --no-progress
      --input app.tar
      --severity MEDIUM,HIGH,CRITICAL
      --exit-code 42
      --exit-on-eol 43
  # Normally you would not allow failures, but this makes it explicit that the scan succeeded, while issues are found.
  allow_failure:
    exit_codes:
      - 42
      - 43

infrastructure as code:
  stage: security-scan
  image:
    name: bridgecrew/checkov
    entrypoint: [ "" ]
  script:
    - checkov
        --directory "${CI_PROJECT_DIR}"
        --quiet
  # Normally you would not allow failures, but this makes it explicit that the scan succeeded, while issues are found.
  allow_failure:
    exit_codes:
      - 1  # means a successful scan, but with found issues. Otherwise it would exit 2
