AWSTemplateFormatVersion: 2010-09-09
Resources:
  TestRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "app"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: "MUTABLE"
