name: security-scanning-quickstarts
on: [push, workflow_dispatch]
jobs:
  build-container:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - uses: actions/checkout@v1
      - run: >-
          /kaniko/executor
          --context "${GITHUB_WORKSPACE}"
          --dockerfile "${GITHUB_WORKSPACE}/Dockerfile"
          --no-push
          --destination app
          --tar-path app.tar
      - name: Upload image tar
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: app.tar

  scan-container:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: aquasec/trivy
    steps:
      - name: Download image tar
        uses: actions/download-artifact@v3
        with:
          name: image
      - run: >-
          trivy image
          --no-progress
          --input app.tar
          --severity MEDIUM,HIGH,CRITICAL
          --exit-code 1
          --exit-on-eol 2
