name: security-scanning-quickstarts
on: [push, workflow_dispatch]
jobs:
  build-container:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - uses: actions/checkout@v1
      - run: |
          /kaniko/executor \
            --context "${CI_PROJECT_DIR}" \
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
            --no-push \
            --destination app \
            --tar-path app.tar
